import editorialDocumento from "@/assets/editorial-documento.jpg";
import editorialLivro from "@/assets/editorial-livro.jpg";
import editorialJustica from "@/assets/editorial-justica.jpg";
import heroTribunal from "@/assets/hero-tribunal.jpg";
import heroStf from "@/assets/hero-stf.jpg";
import heroCourthouse from "@/assets/hero-courthouse.jpg";
import heroLegalDesk from "@/assets/hero-legal-desk.jpg";
import heroSupremo from "@/assets/hero-supremo.jpg";
import type {
  AdminUserRecord,
  AuthorRecord,
  ContentPerformanceRecord,
  ContentDecisionMetaRecord,
  ContentExposureRecord,
  ContentMediaRecord,
  ContentRecord,
  ContentSeoRecord,
  EditoriaRecord,
  HomeZoneConfigRecord,
  NewsletterEditionRecord,
  RolePermissionRecord,
  SiteConfigRecord,
  SourceRecord,
  WorkflowCommentRecord,
  WorkflowEventRecord,
} from "./types";

export const editorialImages: Record<string, string> = {
  "editorial-documento": editorialDocumento,
  "editorial-livro": editorialLivro,
  "editorial-justica": editorialJustica,
  "hero-tribunal": heroTribunal,
  "hero-stf": heroStf,
  "hero-courthouse": heroCourthouse,
  "hero-legal-desk": heroLegalDesk,
  "hero-supremo": heroSupremo,
};

export const editorias: EditoriaRecord[] = [
  {
    id: "tributario",
    name: "Tributário",
    slug: "tributario",
    description: "Impostos, contribuições, reforma tributária e jurisprudência fiscal.",
    longDescription: "Cobertura editorial dedicada a tributos, contencioso fiscal, reforma tributária e jurisprudência dos tribunais superiores.",
    seoDescription: "Cobertura editorial jurídica sobre tributário.",
    menuOrder: 1,
    isVisibleInNavigation: true,
    isFeaturedOnHome: true,
    defaultImageId: "hero-supremo",
    editorResponsible: "Ana Beatriz Duarte",
  },
  {
    id: "empresarial",
    name: "Empresarial",
    slug: "empresarial",
    description: "Societário, contratos, M&A, recuperação judicial e compliance.",
    longDescription: "Conteúdos sobre empresas, contratos, governança, recuperação judicial e mercado regulado.",
    seoDescription: "Cobertura editorial sobre societário, contratos e recuperação judicial.",
    menuOrder: 2,
    isVisibleInNavigation: true,
    isFeaturedOnHome: true,
    defaultImageId: "hero-courthouse",
    editorResponsible: "João Pedro Silva",
  },
  {
    id: "imobiliario",
    name: "Imobiliário",
    slug: "imobiliario",
    description: "Direito imobiliário, registros, usucapião e incorporações.",
    longDescription: "Cobertura sobre mercado imobiliário, registros, usucapião, incorporações e regularização fundiária.",
    seoDescription: "Conteúdos jurídicos sobre direito imobiliário e regularização fundiária.",
    menuOrder: 3,
    isVisibleInNavigation: true,
    isFeaturedOnHome: true,
    defaultImageId: "hero-legal-desk",
    editorResponsible: "Mariana Costa",
  },
  {
    id: "sucessorio",
    name: "Sucessório",
    slug: "sucessorio",
    description: "Herança, inventário, testamento, partilha e planejamento sucessório.",
    longDescription: "Análises e notícias sobre herança, inventário, planejamento sucessório e disputas patrimoniais.",
    seoDescription: "Cobertura editorial sobre sucessões, inventários e planejamento patrimonial.",
    menuOrder: 4,
    isVisibleInNavigation: true,
    isFeaturedOnHome: true,
    defaultImageId: "editorial-documento",
    editorResponsible: "Ricardo Alves",
  },
];

export const authors: AuthorRecord[] = [
  {
    id: "ana-beatriz-duarte",
    name: "Ana Beatriz Duarte",
    publicName: "Profa. Ana Beatriz Souza",
    role: "Editora Sênior",
    email: "ana@veredito.com",
    shortBio: "Jornalista especializada em Direito Tributário.",
    longBio: "Jornalista especializada em Direito Tributário com quinze anos de experiência em cobertura de tribunais superiores.",
    slug: "ana-beatriz-duarte",
    specialty: "Direito Tributário",
    jobTitle: "Editora de Tributário",
    type: "internal",
    isPublicPageEnabled: true,
  },
  {
    id: "carlos-mendes",
    name: "Carlos Mendes",
    publicName: "Carlos Mendes",
    role: "Repórter Jurídico",
    email: "carlos@veredito.com",
    shortBio: "Repórter jurídico com foco em cobertura regulatória.",
    slug: "carlos-mendes",
    specialty: "Direito Empresarial",
    jobTitle: "Repórter Especial",
    type: "internal",
    isPublicPageEnabled: true,
  },
  {
    id: "fernanda-lima",
    name: "Fernanda Lima",
    publicName: "Dr. Fernando Maia",
    role: "Colunista",
    email: "fernanda@veredito.com",
    shortBio: "Professor e articulista de Direito Empresarial.",
    slug: "fernanda-lima",
    specialty: "Direito Empresarial",
    jobTitle: "Colunista",
    type: "columnist",
    isPublicPageEnabled: true,
  },
  {
    id: "ricardo-alves",
    name: "Ricardo Alves",
    publicName: "Prof. Carlos Eduardo Lima",
    role: "Colunista",
    email: "ricardo@veredito.com",
    shortBio: "Professor e colunista em temas constitucionais e imobiliários.",
    slug: "ricardo-alves",
    specialty: "Direito Imobiliário",
    jobTitle: "Colunista",
    type: "columnist",
    isPublicPageEnabled: true,
  },
  {
    id: "mariana-costa",
    name: "Mariana Costa",
    publicName: "Dra. Mariana Costa",
    role: "Repórter Jurídica",
    email: "mariana@veredito.com",
    shortBio: "Cobertura do STF e tribunais superiores.",
    slug: "mariana-costa",
    specialty: "Direito Imobiliário",
    jobTitle: "Repórter Jurídica",
    type: "internal",
    isPublicPageEnabled: true,
  },
];

export const sources: SourceRecord[] = [
  { id: "stf", name: "Supremo Tribunal Federal", shortName: "STF", type: "court", officialUrl: "https://portal.stf.jus.br", defaultEditoriaId: "tributario", monitoringEnabled: true, priority: "high", monitoredTags: ["ICMS", "PIS/Cofins"], internalOwner: "Ana Beatriz Duarte", reliability: "high", origin: "manual" },
  { id: "stj", name: "Superior Tribunal de Justiça", shortName: "STJ", type: "court", officialUrl: "https://www.stj.jus.br", defaultEditoriaId: "imobiliario", monitoringEnabled: true, priority: "high", monitoredTags: ["Usucapião", "ITBI"], internalOwner: "Mariana Costa", reliability: "high", origin: "manual" },
  { id: "cnj", name: "Conselho Nacional de Justiça", shortName: "CNJ", type: "regulator", officialUrl: "https://www.cnj.jus.br", defaultEditoriaId: "empresarial", monitoringEnabled: true, priority: "medium", monitoredTags: ["IA", "Judiciário"], internalOwner: "Carlos Mendes", reliability: "medium", origin: "rss" },
];

export const contents: ContentRecord[] = [
  {
    id: "stf-icms-transferencia",
    type: "decision",
    title: "STF define nova tese sobre ICMS em transferência interestadual e altera cenário fiscal de 12 estados",
    subtitle: "Decisão afeta diretamente a arrecadação estadual e reabre debates sobre a guerra fiscal.",
    lead: "O Supremo Tribunal Federal consolidou entendimento com impacto imediato sobre a tributação em operações interestaduais.",
    summaryCard: "Decisão unânime da Corte impacta diretamente a arrecadação estadual e obriga governadores a revisarem suas legislações tributárias.",
    body: "A decisão proferida nesta semana marca um ponto de inflexão na jurisprudência brasileira sobre o tema, estabelecendo precedentes que devem orientar os tribunais inferiores nos próximos anos.\n\nSegundo especialistas ouvidos pela redação do Veredito, a tese fixada pelo tribunal tem potencial para impactar diretamente milhares de processos em tramitação, além de alterar significativamente o planejamento jurídico de empresas e contribuintes.\n\nO relator do caso fundamentou seu voto em uma análise sistemática da Constituição Federal, considerando não apenas o dispositivo específico em debate, mas também os princípios gerais que regem a matéria.\n\nPara os contribuintes, a decisão traz maior segurança jurídica e previsibilidade, elementos essenciais para o planejamento fiscal de longo prazo.",
    slug: "stf-icms-transferencia",
    status: "published",
    editorialPriority: "critical",
    editoriaId: "tributario",
    authorId: "ana-beatriz-duarte",
    sourceId: "stf",
    featuredImageId: "hero-supremo",
    publishedAt: "2026-03-24T14:30:00Z",
    updatedAt: "2026-03-24T15:00:00Z",
    readingTime: 8,
    tags: ["STF", "ICMS", "Federalismo Fiscal", "Jurisprudência"],
    relatedContentIds: ["stf-pis-cofins", "reforma-tributaria-contratos"],
  },
  {
    id: "nova-lei-recuperacao",
    type: "news",
    title: "Nova lei de recuperação judicial entra em vigor com mudanças significativas para credores",
    lead: "Texto altera prazos, amplia instrumentos de negociação e muda a relação entre empresas e credores.",
    summaryCard: "Mudanças afetam diretamente o contencioso empresarial e a estratégia de renegociação de dívidas.",
    body: "A nova legislação amplia instrumentos processuais e altera o equilíbrio entre devedores e credores em processos de recuperação judicial.\n\nEspecialistas avaliam que as mudanças trazem mais previsibilidade, mas exigem adaptação rápida de departamentos jurídicos e financeiros.",
    slug: "nova-lei-recuperacao",
    status: "published",
    editorialPriority: "high",
    editoriaId: "empresarial",
    authorId: "carlos-mendes",
    featuredImageId: "hero-courthouse",
    publishedAt: "2026-03-24T13:00:00Z",
    updatedAt: "2026-03-24T13:10:00Z",
    readingTime: 5,
    tags: ["Recuperação Judicial", "Credores"],
    relatedContentIds: [],
  },
  {
    id: "stj-usucapiao",
    type: "decision",
    title: "STJ consolida entendimento sobre usucapião em imóveis urbanos irregulares",
    lead: "Julgamento reforça critérios para reconhecimento da posse e regularização fundiária.",
    summaryCard: "Corte uniformiza critérios práticos para disputas sobre imóveis urbanos irregulares.",
    body: "O entendimento consolida critérios para ações envolvendo imóveis urbanos sem registro regular.\n\nAdvogados da área imobiliária afirmam que a decisão traz previsibilidade para litígios de massa e regularizações administrativas.",
    slug: "stj-usucapiao",
    status: "published",
    editorialPriority: "high",
    editoriaId: "imobiliario",
    authorId: "mariana-costa",
    sourceId: "stj",
    featuredImageId: "hero-legal-desk",
    publishedAt: "2026-03-23T18:30:00Z",
    updatedAt: "2026-03-23T18:30:00Z",
    readingTime: 6,
    tags: ["STJ", "Usucapião", "Imobiliário"],
    relatedContentIds: [],
  },
  {
    id: "tjsp-heranca-companheiro",
    type: "decision",
    title: "TJ-SP reconhece direito de companheiro em herança mesmo sem testamento formal",
    lead: "Acórdão amplia proteção patrimonial em união estável com repercussão prática para inventários.",
    summaryCard: "Decisão reforça entendimento protetivo sobre sucessão patrimonial sem testamento.",
    body: "A decisão reforça uma leitura protetiva da união estável e seus efeitos patrimoniais em disputas sucessórias.\n\nA repercussão prática deve ser imediata em inventários judiciais e planejamentos sucessórios preventivos.",
    slug: "tjsp-heranca-companheiro",
    status: "published",
    editorialPriority: "medium",
    editoriaId: "sucessorio",
    authorId: "mariana-costa",
    featuredImageId: "editorial-documento",
    publishedAt: "2026-03-23T12:00:00Z",
    updatedAt: "2026-03-23T12:00:00Z",
    readingTime: 5,
    tags: ["Herança", "União Estável"],
    relatedContentIds: [],
  },
  {
    id: "reforma-tributaria-contratos",
    type: "article",
    title: "O impacto da reforma tributária nos contratos de longo prazo",
    lead: "Análise aprofundada sobre a necessidade de redimensionar riscos e cláusulas de reequilíbrio.",
    summaryCard: "Como a transição do sistema tributário afeta contratos de concessão, PPPs e acordos plurianuais.",
    body: "A reforma tributária muda premissas estruturais de contratos de longo prazo e exige revisão técnica de cláusulas de precificação, reequilíbrio e repartição de riscos.\n\nO ponto central não está apenas na carga tributária final, mas no período de transição e na convivência de regimes distintos.",
    slug: "reforma-tributaria-contratos",
    status: "published",
    editorialPriority: "high",
    editoriaId: "tributario",
    authorId: "ana-beatriz-duarte",
    featuredImageId: "editorial-documento",
    publishedAt: "2026-03-24T09:00:00Z",
    updatedAt: "2026-03-24T10:00:00Z",
    readingTime: 12,
    tags: ["Reforma Tributária", "Contratos"],
    relatedContentIds: ["stf-icms-transferencia"],
  },
  {
    id: "compliance-responsabilidade",
    type: "article",
    title: "Compliance e a nova era da responsabilidade corporativa no Brasil",
    lead: "A pressão regulatória transformou governança em elemento central de valor empresarial.",
    summaryCard: "Como as empresas brasileiras estão se adaptando às novas exigências regulatórias.",
    body: "A evolução regulatória mudou o papel do compliance, que deixou de ser área acessória para se tornar estrutura de gestão de risco reputacional e jurídico.\n\nEmpresas que internalizam governança mais cedo reduzem custo de litigância e ganham vantagem competitiva.",
    slug: "compliance-responsabilidade",
    status: "published",
    editorialPriority: "medium",
    editoriaId: "empresarial",
    authorId: "fernanda-lima",
    featuredImageId: "editorial-livro",
    publishedAt: "2026-03-23T16:00:00Z",
    updatedAt: "2026-03-23T16:00:00Z",
    readingTime: 9,
    tags: ["Compliance", "Governança"],
    relatedContentIds: [],
  },
  {
    id: "ativismo-judicial",
    type: "article",
    title: "Os limites do ativismo judicial na democracia brasileira contemporânea",
    lead: "Reflexão sobre a tensão entre protagonismo judicial, legitimidade democrática e separação de poderes.",
    summaryCard: "Análise sobre o equilíbrio entre a atuação proativa do Judiciário e a separação de poderes.",
    body: "O debate sobre ativismo judicial precisa sair da retórica e voltar aos critérios de legitimidade institucional.\n\nA expansão do protagonismo judicial produz ganhos de proteção em alguns contextos, mas também riscos de erosão do espaço deliberativo dos demais poderes.",
    slug: "ativismo-judicial",
    status: "published",
    editorialPriority: "medium",
    editoriaId: "imobiliario",
    authorId: "ricardo-alves",
    featuredImageId: "editorial-justica",
    publishedAt: "2026-03-22T11:00:00Z",
    updatedAt: "2026-03-22T11:00:00Z",
    readingTime: 15,
    tags: ["Ativismo Judicial", "Democracia"],
    relatedContentIds: [],
  },
  {
    id: "precatorios-reforma",
    type: "opinion",
    title: "A necessidade de uma reforma no sistema de precatórios",
    lead: "O sistema atual acumula ineficiência, insegurança e dificuldade de planejamento fiscal.",
    summaryCard: "Uma defesa de modernização do sistema de precatórios sob a ótica fiscal e institucional.",
    body: "O sistema de precatórios brasileiro precisa ser redesenhado com foco em previsibilidade, responsabilidade federativa e segurança do credor.\n\nSem uma reforma estrutural, o passivo continuará sendo tratado como contingência política, e não como obrigação estatal programável.",
    slug: "precatorios-reforma",
    status: "published",
    editorialPriority: "medium",
    editoriaId: "tributario",
    authorId: "ana-beatriz-duarte",
    featuredImageId: "hero-supremo",
    publishedAt: "2026-03-24T08:00:00Z",
    updatedAt: "2026-03-24T08:00:00Z",
    readingTime: 8,
    tags: ["Precatórios", "Opinião"],
    relatedContentIds: [],
  },
  {
    id: "lei-falencias",
    type: "opinion",
    title: "Por que o Brasil precisa modernizar sua Lei de Falências",
    lead: "O desenho atual ainda impõe fricções que dificultam reorganização econômica eficiente.",
    summaryCard: "Comparação com modelos internacionais mostra gargalos persistentes da legislação brasileira.",
    body: "A Lei de Falências evoluiu, mas ainda preserva travas procedimentais que ampliam custo de transação e reduzem eficiência do sistema.\n\nA modernização deve ser orientada por liquidez, preservação de atividade econômica e racionalidade dos incentivos.",
    slug: "lei-falencias",
    status: "published",
    editorialPriority: "medium",
    editoriaId: "empresarial",
    authorId: "fernanda-lima",
    featuredImageId: "hero-courthouse",
    publishedAt: "2026-03-23T09:00:00Z",
    updatedAt: "2026-03-23T09:00:00Z",
    readingTime: 7,
    tags: ["Falências", "Opinião"],
    relatedContentIds: [],
  },
  {
    id: "supremo-liberdades",
    type: "opinion",
    title: "O papel do Supremo na proteção das liberdades individuais",
    lead: "A proteção judicial de direitos fundamentais não deve dispensar prudência institucional.",
    summaryCard: "Análise sobre o papel do STF na defesa das liberdades em contextos de alta tensão política.",
    body: "O Supremo ocupa posição central na proteção de liberdades individuais, mas essa função exige autocontenção argumentativa e rigor metodológico.\n\nA credibilidade institucional depende tanto do resultado quanto da qualidade pública da fundamentação.",
    slug: "supremo-liberdades",
    status: "published",
    editorialPriority: "medium",
    editoriaId: "imobiliario",
    authorId: "ricardo-alves",
    featuredImageId: "hero-tribunal",
    publishedAt: "2026-03-22T08:00:00Z",
    updatedAt: "2026-03-22T08:00:00Z",
    readingTime: 10,
    tags: ["STF", "Liberdades"],
    relatedContentIds: [],
  },
  {
    id: "senado-prescricao",
    type: "news",
    title: "Senado aprova projeto que altera regras de prescrição tributária",
    lead: "Mudança afeta diretamente planejamento fiscal de empresas e pode reduzir contencioso.",
    summaryCard: "Projeto avança no Senado e reabre debate sobre segurança jurídica tributária.",
    body: "A proposta altera marcos prescricionais e reacende discussão sobre previsibilidade em matéria tributária.",
    slug: "senado-prescricao",
    status: "published",
    editorialPriority: "high",
    editoriaId: "tributario",
    authorId: "carlos-mendes",
    featuredImageId: "hero-stf",
    publishedAt: "2026-03-24T14:32:00Z",
    updatedAt: "2026-03-24T14:32:00Z",
    readingTime: 5,
    tags: ["Senado", "Prescrição"],
    relatedContentIds: [],
  },
  {
    id: "oab-nota-tecnica",
    type: "news",
    title: "OAB publica nota técnica contra proposta de emenda constitucional",
    lead: "Documento critica dispositivos que poderiam fragilizar a independência do Judiciário.",
    summaryCard: "Manifestação técnica da OAB amplia pressão institucional sobre a proposta.",
    body: "A nota técnica enumera riscos institucionais e sustenta que a proposta exige maior debate público e revisão de dispositivos centrais.",
    slug: "oab-nota-tecnica",
    status: "published",
    editorialPriority: "medium",
    editoriaId: "empresarial",
    authorId: "carlos-mendes",
    featuredImageId: "hero-tribunal",
    publishedAt: "2026-03-24T13:15:00Z",
    updatedAt: "2026-03-24T13:15:00Z",
    readingTime: 4,
    tags: ["OAB", "PEC"],
    relatedContentIds: [],
  },
  {
    id: "cnj-ia-judiciario",
    type: "news",
    title: "CNJ regulamenta uso de inteligência artificial no Judiciário",
    lead: "Resolução estabelece diretrizes para uso de IA em decisões judiciais e gestão processual.",
    summaryCard: "Norma cria parâmetros nacionais para uso de IA no Judiciário.",
    body: "A regulamentação delimita critérios de transparência, revisão humana e governança de sistemas automatizados.",
    slug: "cnj-ia-judiciario",
    status: "published",
    editorialPriority: "high",
    editoriaId: "imobiliario",
    authorId: "mariana-costa",
    sourceId: "cnj",
    featuredImageId: "editorial-livro",
    publishedAt: "2026-03-24T12:48:00Z",
    updatedAt: "2026-03-24T12:48:00Z",
    readingTime: 6,
    tags: ["CNJ", "IA"],
    relatedContentIds: [],
  },
  {
    id: "stf-pis-cofins",
    type: "decision",
    title: "Plenário afasta incidência de PIS/Cofins sobre receitas financeiras de exportadoras",
    lead: "Julgamento reduz pressão tributária e fortalece imunidade das exportações.",
    summaryCard: "Decisão relevante do STF com impacto alto para exportadoras.",
    body: "A Corte entendeu que a incidência sobre receitas financeiras vinculadas à atividade exportadora contraria a lógica constitucional de desoneração.",
    slug: "stf-pis-cofins",
    status: "published",
    editorialPriority: "high",
    editoriaId: "tributario",
    authorId: "ana-beatriz-duarte",
    sourceId: "stf",
    featuredImageId: "hero-supremo",
    publishedAt: "2026-03-23T10:00:00Z",
    updatedAt: "2026-03-23T10:00:00Z",
    readingTime: 8,
    tags: ["STF", "PIS/Cofins"],
    relatedContentIds: ["stf-icms-transferencia"],
  },
  {
    id: "stj-itbi",
    type: "decision",
    title: "Primeira Seção define que ITBI deve incidir sobre valor declarado na transação imobiliária",
    lead: "Julgamento uniformiza controvérsia recorrente entre municípios e contribuintes.",
    summaryCard: "Entendimento do STJ redefine base prática de cálculo do ITBI.",
    body: "O STJ consolidou a tese de que a base de cálculo deve observar o valor declarado na transação, salvo comprovação administrativa consistente em sentido diverso.",
    slug: "stj-itbi",
    status: "published",
    editorialPriority: "high",
    editoriaId: "imobiliario",
    authorId: "mariana-costa",
    sourceId: "stj",
    featuredImageId: "hero-courthouse",
    publishedAt: "2026-03-22T10:00:00Z",
    updatedAt: "2026-03-22T10:00:00Z",
    readingTime: 6,
    tags: ["STJ", "ITBI"],
    relatedContentIds: [],
  },
];

export const exposures: ContentExposureRecord[] = [
  { contentId: "stf-icms-transferencia", isPublished: true, isHomeFeatured: true, homeVisibility: true, homeSlotType: "headline", homeZone: "headline", homeOrder: 1, isUrgent: true, urgentTitle: "STF suspende efeitos de lei estadual sobre ICMS", urgentStartsAt: "2026-03-24T14:00:00Z", urgentExpiresAt: "2026-03-24T20:00:00Z", urgentPriority: 1, isNewsletterFeatured: true, isArchivedPublicly: false },
  { contentId: "nova-lei-recuperacao", isPublished: true, isHomeFeatured: true, homeVisibility: true, homeSlotType: "secondary", homeZone: "secondary_highlights", homeOrder: 1, isUrgent: false, isNewsletterFeatured: false, isArchivedPublicly: false },
  { contentId: "stj-usucapiao", isPublished: true, isHomeFeatured: true, homeVisibility: true, homeSlotType: "secondary", homeZone: "secondary_highlights", homeOrder: 2, isUrgent: false, isNewsletterFeatured: false, isArchivedPublicly: false },
  { contentId: "tjsp-heranca-companheiro", isPublished: true, isHomeFeatured: true, homeVisibility: true, homeSlotType: "secondary", homeZone: "secondary_highlights", homeOrder: 3, isUrgent: false, isNewsletterFeatured: false, isArchivedPublicly: false },
  { contentId: "reforma-tributaria-contratos", isPublished: true, isHomeFeatured: true, homeVisibility: true, homeSlotType: "article", homeZone: "articles_analysis", homeOrder: 1, isUrgent: false, isNewsletterFeatured: true, isArchivedPublicly: false },
  { contentId: "compliance-responsabilidade", isPublished: true, isHomeFeatured: true, homeVisibility: true, homeSlotType: "article", homeZone: "articles_analysis", homeOrder: 2, isUrgent: false, isNewsletterFeatured: true, isArchivedPublicly: false },
  { contentId: "ativismo-judicial", isPublished: true, isHomeFeatured: true, homeVisibility: true, homeSlotType: "article", homeZone: "articles_analysis", homeOrder: 3, isUrgent: false, isNewsletterFeatured: false, isArchivedPublicly: false },
  { contentId: "precatorios-reforma", isPublished: true, isHomeFeatured: true, homeVisibility: true, homeSlotType: "opinion", homeZone: "opinion", homeOrder: 1, isUrgent: false, isNewsletterFeatured: false, isArchivedPublicly: false },
  { contentId: "lei-falencias", isPublished: true, isHomeFeatured: true, homeVisibility: true, homeSlotType: "opinion", homeZone: "opinion", homeOrder: 2, isUrgent: false, isNewsletterFeatured: false, isArchivedPublicly: false },
  { contentId: "supremo-liberdades", isPublished: true, isHomeFeatured: true, homeVisibility: true, homeSlotType: "opinion", homeZone: "opinion", homeOrder: 3, isUrgent: false, isNewsletterFeatured: false, isArchivedPublicly: false },
  { contentId: "senado-prescricao", isPublished: true, isHomeFeatured: true, homeVisibility: true, homeSlotType: "list", homeZone: "latest_news", homeOrder: 1, isUrgent: true, urgentTitle: "Senado aprova projeto que altera regras de prescrição tributária", urgentStartsAt: "2026-03-24T14:32:00Z", urgentExpiresAt: "2026-03-24T22:00:00Z", urgentPriority: 2, isNewsletterFeatured: false, isArchivedPublicly: false },
  { contentId: "oab-nota-tecnica", isPublished: true, isHomeFeatured: true, homeVisibility: true, homeSlotType: "list", homeZone: "latest_news", homeOrder: 2, isUrgent: false, isNewsletterFeatured: false, isArchivedPublicly: false },
  { contentId: "cnj-ia-judiciario", isPublished: true, isHomeFeatured: true, homeVisibility: true, homeSlotType: "list", homeZone: "latest_news", homeOrder: 3, isUrgent: false, isNewsletterFeatured: false, isArchivedPublicly: false },
  { contentId: "stf-pis-cofins", isPublished: true, isHomeFeatured: true, homeVisibility: true, homeSlotType: "decision", homeZone: "recent_decisions", homeOrder: 1, isUrgent: false, isNewsletterFeatured: true, isArchivedPublicly: false },
  { contentId: "stj-itbi", isPublished: true, isHomeFeatured: true, homeVisibility: true, homeSlotType: "decision", homeZone: "recent_decisions", homeOrder: 2, isUrgent: false, isNewsletterFeatured: false, isArchivedPublicly: false },
];

export const seo: ContentSeoRecord[] = contents.map((content) => ({
  contentId: content.id,
  seoTitle: content.title,
  seoDescription: content.summaryCard ?? content.lead,
  ogTitle: content.title,
  ogDescription: content.lead,
  canonicalUrl: `https://veredito.com.br/${content.type === "news" ? "noticias" : content.type === "decision" ? "decisoes" : content.type === "article" ? "artigos" : "opiniao"}/${content.slug}`,
  noindex: false,
}));

export const media: ContentMediaRecord[] = contents.map((content) => ({
  contentId: content.id,
  coverImageId: content.featuredImageId,
  socialImageId: content.featuredImageId,
  caption: "Imagem editorial do acervo Veredito",
  credit: "Acervo Veredito",
  altText: `Imagem de capa para ${content.title}`,
  focalPointX: 50,
  focalPointY: 45,
}));

export const decisionMeta: ContentDecisionMetaRecord[] = [
  {
    contentId: "stf-icms-transferencia",
    court: "STF",
    decisionType: "Acórdão",
    rapporteur: "Min. Roberto Barroso",
    caseNumber: "ADI 7.633/DF",
    judgmentDate: "2026-03-24",
    thesis: "É inconstitucional lei estadual que concede benefício fiscal de ICMS sem prévia autorização do CONFAZ.",
    syllabus: "Fixação de tese sobre guerra fiscal e transferência interestadual.",
    practicalImpact: "high",
    officialUrl: "https://portal.stf.jus.br/",
    affectedTheme: "ICMS",
  },
  {
    contentId: "stj-usucapiao",
    court: "STJ",
    decisionType: "Acórdão",
    rapporteur: "Min. Ricardo Villas Bôas Cueva",
    caseNumber: "REsp 1.234.567/SP",
    judgmentDate: "2026-03-23",
    practicalImpact: "high",
    officialUrl: "https://www.stj.jus.br/",
    affectedTheme: "Usucapião",
  },
  {
    contentId: "tjsp-heranca-companheiro",
    court: "TJ-SP",
    decisionType: "Acórdão",
    rapporteur: "Des. Ana Maria Prado",
    caseNumber: "1001234-55.2025.8.26.0100",
    judgmentDate: "2026-03-23",
    practicalImpact: "medium",
    affectedTheme: "Herança",
  },
  {
    contentId: "stf-pis-cofins",
    court: "STF",
    decisionType: "Acórdão",
    rapporteur: "Min. Cristiano Zanin",
    caseNumber: "RE 998.765/DF",
    judgmentDate: "2026-03-23",
    practicalImpact: "high",
    affectedTheme: "PIS/Cofins",
  },
  {
    contentId: "stj-itbi",
    court: "STJ",
    decisionType: "Recurso Repetitivo",
    rapporteur: "Min. Gurgel de Faria",
    caseNumber: "REsp 1.111.222/SP",
    judgmentDate: "2026-03-22",
    practicalImpact: "high",
    affectedTheme: "ITBI",
  },
];

export const homeZoneConfigs: HomeZoneConfigRecord[] = [
  {
    key: "urgent_bar",
    title: "Faixa urgente",
    mode: "automatic",
    maxItems: 3,
    allowedTypes: ["news", "decision"],
    allowedPriorities: ["high", "critical"],
    allowedStatuses: ["published"],
    dateWindowDays: 2,
    requireHomeEligibility: true,
    sort: "priority_desc",
    pinnedContentIds: [],
    fallbackToAutomatic: true,
  },
  {
    key: "headline",
    title: "Manchete principal",
    mode: "hybrid",
    maxItems: 1,
    allowedTypes: ["news", "decision", "article"],
    allowedPriorities: ["medium", "high", "critical"],
    allowedStatuses: ["published"],
    dateWindowDays: 5,
    requireHomeEligibility: true,
    sort: "priority_desc",
    pinnedContentIds: ["stf-icms-transferencia"],
    fallbackToAutomatic: true,
  },
  {
    key: "secondary_highlights",
    title: "Destaques secundários",
    mode: "hybrid",
    maxItems: 3,
    allowedTypes: ["news", "decision"],
    allowedPriorities: ["medium", "high", "critical"],
    allowedStatuses: ["published"],
    dateWindowDays: 7,
    requireHomeEligibility: true,
    sort: "priority_desc",
    pinnedContentIds: ["nova-lei-recuperacao", "stj-usucapiao", "tjsp-heranca-companheiro"],
    fallbackToAutomatic: true,
  },
  {
    key: "latest_news",
    title: "Últimas notícias",
    mode: "automatic",
    maxItems: 7,
    allowedTypes: ["news"],
    allowedPriorities: ["low", "medium", "high", "critical"],
    allowedStatuses: ["published"],
    dateWindowDays: 7,
    requireHomeEligibility: true,
    sort: "published_desc",
    pinnedContentIds: [],
    fallbackToAutomatic: true,
  },
  {
    key: "recent_decisions",
    title: "Decisões recentes",
    mode: "automatic",
    maxItems: 4,
    allowedTypes: ["decision"],
    allowedPriorities: ["medium", "high", "critical"],
    allowedStatuses: ["published"],
    dateWindowDays: 14,
    requireHomeEligibility: true,
    sort: "published_desc",
    pinnedContentIds: [],
    fallbackToAutomatic: true,
  },
  {
    key: "articles_analysis",
    title: "Artigos & análises",
    mode: "automatic",
    maxItems: 3,
    allowedTypes: ["article"],
    allowedPriorities: ["medium", "high", "critical"],
    allowedStatuses: ["published"],
    dateWindowDays: 30,
    requireHomeEligibility: true,
    sort: "published_desc",
    pinnedContentIds: [],
    fallbackToAutomatic: true,
  },
  {
    key: "opinion",
    title: "Opinião",
    mode: "automatic",
    maxItems: 3,
    allowedTypes: ["opinion"],
    allowedPriorities: ["medium", "high", "critical"],
    allowedStatuses: ["published"],
    dateWindowDays: 30,
    requireHomeEligibility: true,
    sort: "published_desc",
    pinnedContentIds: [],
    fallbackToAutomatic: true,
  },
  {
    key: "editorias",
    title: "Editorias",
    mode: "automatic",
    maxItems: 4,
    allowedTypes: [],
    allowedPriorities: ["low", "medium", "high", "critical"],
    allowedStatuses: ["published"],
    dateWindowDays: 30,
    requireHomeEligibility: true,
    sort: "published_desc",
    pinnedContentIds: [],
    fallbackToAutomatic: true,
  },
  {
    key: "newsletter",
    title: "Newsletter",
    mode: "manual",
    maxItems: 1,
    allowedTypes: [],
    allowedPriorities: ["low", "medium", "high", "critical"],
    allowedStatuses: ["published"],
    dateWindowDays: 30,
    requireHomeEligibility: false,
    sort: "published_desc",
    pinnedContentIds: [],
    fallbackToAutomatic: true,
  },
];

export const workflowComments: WorkflowCommentRecord[] = [
  {
    id: "comment-stf-1",
    contentId: "stf-icms-transferencia",
    authorName: "Ana Beatriz Duarte",
    body: "Confirmar se a tese firmada já está refletida no resumo do card antes de manter como manchete.",
    createdAt: "2026-03-24T15:10:00Z",
  },
];

export const workflowEvents: WorkflowEventRecord[] = [
  {
    id: "event-stf-1",
    contentId: "stf-icms-transferencia",
    fromStatus: "approved",
    toStatus: "published",
    actorName: "Ana Beatriz Duarte",
    createdAt: "2026-03-24T15:15:00Z",
    note: "Publicado após validação jurídica.",
  },
];

export const siteConfig: SiteConfigRecord = {
  siteName: "Veredito",
  siteDescription: "Jornalismo jurídico com profundidade e rigor editorial.",
  seoTitleDefault: "Veredito — Jornalismo Jurídico",
  seoDescriptionDefault: "Análises, decisões e opinião sobre o cenário jurídico brasileiro.",
  newsletterLabel: "Curadoria editorial",
  analyticsId: "",
  editorialAlertsEmail: "redacao@veredito.com.br",
  currentAdminUserId: "editor-chefe",
  homeNewsletterEnabled: true,
};

export const rolePermissions: RolePermissionRecord[] = [
  { role: "admin", permissions: ["manage_users", "publish", "approve", "edit_home", "manage_settings", "manage_sources", "manage_editorias", "manage_authors", "edit_content", "submit_review", "legal_review", "manage_newsletter"] },
  { role: "editor-chefe", permissions: ["publish", "approve", "edit_home", "manage_editorias", "manage_authors", "edit_content", "submit_review"] },
  { role: "editor", permissions: ["edit_content", "submit_review"] },
  { role: "revisor_juridico", permissions: ["legal_review"] },
  { role: "autor", permissions: ["edit_own_content"] },
  { role: "colunista", permissions: ["edit_own_content"] },
  { role: "operador_newsletter", permissions: ["manage_newsletter"] },
];

export const adminUsers: AdminUserRecord[] = [
  { id: "editor-chefe", name: "Editor Chefe", email: "editor@veredito.com", role: "admin", status: "active" },
  { id: "ana", name: "Ana Beatriz Duarte", email: "ana@veredito.com", role: "editor-chefe", status: "active" },
  { id: "carlos", name: "Carlos Mendes", email: "carlos@veredito.com", role: "editor", status: "active" },
  { id: "mariana", name: "Mariana Costa", email: "mariana@veredito.com", role: "revisor_juridico", status: "active" },
];

export const contentPerformance: ContentPerformanceRecord[] = [
  { contentId: "stf-icms-transferencia", views24h: 2105, views7d: 6120, views30d: 15820, homeClicks: 420, homeImpressions: 3000, newsletterClicks: 96 },
  { contentId: "reforma-tributaria-contratos", views24h: 1284, views7d: 3902, views30d: 9320, homeClicks: 280, homeImpressions: 2200, newsletterClicks: 72 },
  { contentId: "nova-lei-recuperacao", views24h: 876, views7d: 2450, views30d: 7100, homeClicks: 210, homeImpressions: 1900, newsletterClicks: 54 },
  { contentId: "cnj-ia-judiciario", views24h: 654, views7d: 1980, views30d: 5340, homeClicks: 188, homeImpressions: 1750, newsletterClicks: 33 },
  { contentId: "stj-itbi", views24h: 432, views7d: 1650, views30d: 4200, homeClicks: 121, homeImpressions: 1400, newsletterClicks: 25 },
  { contentId: "coluna-sucessorio-digital", views24h: 289, views7d: 920, views30d: 2810, homeClicks: 77, homeImpressions: 1100, newsletterClicks: 18 },
];

export const newsletterEditions: NewsletterEditionRecord[] = [
  {
    id: "newsletter-2026-03-24",
    subject: "Veredito Semanal #43 — STF, recuperação e IA no Judiciário",
    intro: "As decisões e análises que realmente moveram a semana jurídica.",
    headlineContentId: "stf-icms-transferencia",
    contentIds: ["stf-icms-transferencia", "nova-lei-recuperacao", "cnj-ia-judiciario"],
    status: "draft",
  },
  {
    id: "newsletter-2026-03-17",
    subject: "Veredito Semanal #42 — tributário, home e precedentes",
    intro: "Uma leitura curta para entrar na semana já contextualizado.",
    headlineContentId: "reforma-tributaria-contratos",
    contentIds: ["reforma-tributaria-contratos", "stj-itbi", "coluna-sucessorio-digital"],
    status: "sent",
    sentAt: "2026-03-17T11:00:00Z",
  },
];
